name: composable-mapping
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch::pytorch-cuda=11.8
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch=2.4
  - ipykernel
  - matplotlib
  - mypy
  - pip
  - pylint
  - black
  - isort
  - twine
  - pip:
    - nibabel
    - pdoc
    - deformation-inversion-layer >= 1.1.2